language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: GmRAShfaeiNY8rHeM0GHti5Bj7DyZrmrle4rHU4qTtiRKfTbBbUDtGthSfEEzCiUyoG4V0jKlwiaKR4KaUqCL7J0EFkudpY4sqyiaA/5h4YALBB7kO9HVXrzMCxTE+uHz7DQ8eLk1NqXeCRVhhBvXT3RQQ+r4BUTBxsOoFwBRRpMQZ3fFyGovso8bpCznL8VpINJ7i8B0xl4NmcjLFHSpkeZuQe6+gTWv7CNuw7fFMuFnWJuaGctDvrB4xjPCQBh0914g68CZzgYvW7B5Zuju1DBJ5Urp889JKYc7kf4V0jLSLYL2fkpjnwCOuCpVPlH8pb7FBLSH4g5VIJOymK4QVM3L5IVTgctFHdKCAKjTe2/OlTA4llu2mQPrEiMw83/MNqlO152gc2Tqc7bNqrQwGLdJdpxt8Rk9MboHw49NEZU7jfl89dCLKYccuvhjYJd/wKPNRKuDg+MY4UkDIVfAyxSitw9X5/URF3UQfPSEnThoNymSP56l0Yxernb7mwdmQRCqzrhZdQZZ2xDFKNy2l62YzkxW04OUFoCa5Y+oB9bbtK9Hqsfec4gIS6OIzMvbACFVkeeljPxjE7z2/5n7rWaygSiXwmSkvubtetMf7vIlmtVbSeNWdsq19qNQRnTK6mGHbZDtvyz/mYJouvPg2o9BcUNmEXB+lJkJkiZw2w=
  app: Mysterious-cove-68914
  on:
    repo: KennethJMiddleton/GameShelf
