language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: HjDBb49Xp03So6kPCK75g4fdnBQGWCJXyxLUafQXhQmWYat4cxW9tTyGaBaVEyh7lPraRFPhafl3Pg5BePsVFOsHathRSeiIXD6qWpKKNL5TfQkjZbpbllsgj/e3NGmNMhxkeWTOwBdDGxYtOcs/v7JdQVVNpmitwjg4qtEdjdR7kHEfMYTBB2KAmLLPl0F0kTexLTyQlorzTfAJBDHo63LQFlSqTf6TOEUkSe38G+czuHkmu18E0479M40nIx3U7u6jw/mJyZRifGmJ+MQd8sDBS/VT9gIA6dVYbVBk1gUhDBuBqKMe4//wWi1UY/PjP2HFzu2d+bQfIVFKbHWOYlTzlg8t+YQ/5/px6Kf+qE++m2Dwu2wv6gH6XHispmmGEBAXev68zxsVNsg7NQX04SOr5+VZljLilyuRWwkZa4bTdN2GK0Ia1/ZWLo8xV5ad1FLDQqWiH+T3yubTBOZlP16EyZ5Q0Hge9bzEeD21zviQt7eYTLpQGzgaLEaEFmgEvJnsCS92ycCqTh+tikxpdzyYF3Jf69OWX3A/Gj1VCcKA9Fx1QJXDVGuoeV7WcpmpYLBOhnF0unB5EHqHSsD+P44OPZkShJoyBvUPJTn40GHqMQDPSaTY5XRmbMk7ylGUfjsEtzDzRbHkUMlR1mJelN2BsltCMX3XP8kaSMy6p7A=
  app: mysterious-cove-68914
  on:
    repo: KennethJMiddleton/GameShelf
