language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: io9lm3ce71ddSopFQcUmirDfeN+oMBor7GHcKukAt2qtrk9nteOwxr6dIfZxkvQLwGdnG+AQWMDUqmNZFpxAa+D0sWU5qQiinkqxCKxkxXfBlreq9R7sNQ+rP9NrsYIKov+tvtwsJ0NYZGh5O7rHnRFdoa1svptBwKxjZ5/Y41VsNMsCYjUP5kVgbibwd2kkwqy/tXimivngvzK9nSdAvamsu4lPtpd4H8/bXlhLKxgt95iyoo0Zqr/sj1pF3EA4iUCB20lo6An0NWyu8xqeIV2pIpzROOdS6E2cntjnw6DuiRg6Yg831oPb0ixHYOMzco6V8PIroTxt0MCc7DJ0PUK+6LyNe0qobeLNj3oUdm2O8PI8lv+p3mUTwXztFAvPlwBvJm0J6nh9ZCtHY9VYlmoa4exsxPCCTeBAh5H9fbJHwQcHaQGpT6OSrCgclf3qpOtaSstmwnfhFRxv859rk357Mt8mQJ47vZdLJXFUJvgLhuYSS0L7G9bhPJvaoRs6o6wFPJlvRmE+Kg/LOSdSLUyzbliH31BecKXxb5Dpd7+bt/Ww7sJ9+2P2uFulvi81I875gFxFlkxv57ATOqF96NzjGlF9xJgLgT0myEdahNymj2bXc/LOJ0ufPpdGHaqj1Jy8gyumvVJ2y0LeIhI1Peq6COCsB2Hb5ouQTiIq864=
  app: GameShelf
  on:
    repo: KennethJMiddleton/GameShelf
